baseURL = 'https://tabletopgaminghq.netlify.app/'
languageCode = 'en-us'
title = 'Tabletop Gaming HQ'

[params]
  description = "Stay updated on tabletop gaming news with Tabletop Gaming HQ."
  logo = "images/tabletop-gaming-hq.webp"
[services]
  [services.disqus]
    shortname = 'warpainter'

