baseURL = 'https://tabletopgaminghq.netlify.app/'
languageCode = 'en-us'
title = 'Tabletop Gaming HQ'
theme = 'th2-0'
[params]
    description = "Stay updated on tabletop gaming news with Tabletop Gaming HQ."